packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@commitlint/cli": ^21.0.2
  "@commitlint/config-conventional": ^21.0.2
  "@faker-js/faker": 10.4.0
  "@fastify/cors": ^11.1.0
  "@fast-check/vitest": ^0.4.1
  "@types/node": ^24.10.1
  "@types/pg": ^8.15.6
  "@vitest/coverage-v8": ^4.0.15
  fastify: ^5.6.2
  glob: ^13.0.0
  husky: ^9.1.7
  jsdom: ^27.3.0
  lint-staged: ^17.0.7
  nats: ^2.29.3
  pg: ^8.16.3
  prettier: ^3.8.1
  tsx: ^4.20.6
  typescript: ^6.0.3
  vitest: ^4.0.15

onlyBuiltDependencies:
  - esbuild
